name: aesapp
description: AESApp
publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  icons_launcher: ^2.1.3
  hexcolor: ^3.0.1
  firebase_core: ^2.15.1
  firebase_messaging: ^14.6.6
  get: ^4.6.5
  qr_flutter: ^4.1.0
  drift: ^2.11.1
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.3
  logging: ^1.2.0
  supabase_flutter: ^1.10.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  drift_dev: ^2.11.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

icons_launcher:
  image_path: "assets/icons/web/icon-512.png"
  platforms:
    android:
      enable: true
      image_path: "assets/icons/web/icon-512.png"
      adaptive_background_color: '#000000'
      adaptive_foreground_image: "assets/icons/android/ic_launcher_foreground.png"
      adaptive_monochrome_image: "assets/icons/android/ic_launcher_monochrome.png"
    ios:
      enable: true
      image_path: "assets/icons/web/icon-512-maskable.png"
    web:
      enable: true
      image_path: "assets/icons/web/icon-512.png"
      favicon_path: "assets/icons/web/icon-512.png"
    macos:
      enable: true
      image_path: "assets/icons/web/icon-512-maskable.png"
    windows:
      enable: true
      image_path: "assets/icons/web/icon-512.png"
    linux:
      enable: true
      image_path: "assets/icons/web/icon-512.png"

