name: aesapp
description: AESApp
publish_to: 'none'

version: 0.0.23+5

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  icons_launcher: ^2.1.3
  hexcolor: ^3.0.1
  firebase_core: ^3.1.0
  firebase_messaging: ^15.0.1
  get: ^4.6.5
  qr_flutter: ^4.1.0
  path_provider: ^2.0.0
  path: ^1.8.3
  logging: ^1.2.0
  web_socket_channel: ^3.0.0
  basic_utils: ^5.6.1
  shared_preferences: ^2.2.1
  dio: ^5.3.3
  crypto: ^3.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  sn_progress_dialog: ^1.1.3
  bot_toast: ^4.1.3
  collection: ^1.17.2
  dynamic_color: ^1.6.8
  device_info_plus: ^10.0.1
  week_of_year: ^2.2.0
  intl: ^0.19.0
  connectivity_plus: ^6.0.1
  retrofit: ^4.0.3
  universal_html: ^2.2.4
  json_annotation: ^4.8.1
  responsive_grid_list: ^1.4.0
  freezed_annotation: ^2.4.1
  listenable_stream: ^2.0.1
  wear: ^1.1.0
  wearable_rotary: ^2.0.2
  markdown_widget: ^2.3.2+3
  drop_cap_text: ^1.1.3
  infinite_scroll_pagination: ^4.0.0
  web: ^1.0.0
  universal_io: ^2.2.2
  package_info_plus: ^8.0.0
  faabul_color_picker: ^1.1.0

dependency_overrides:
  wear:
    git: https://github.com/aws1313/flutter_wear_plugin.git

  drop_cap_text:
    git:
      url: https://github.com/parlough/drop_cap_text.git
      ref: feat/adapt-for-deprecations

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.6
  retrofit_generator: ^9.1.2
  json_serializable: ^6.6.2
  freezed: ^2.4.6
  hive_generator: ^2.0.1


flutter:
  uses-material-design: true
  #generate: true


icons_launcher:
  image_path: "assets/icons/web/icon-512.png"
  platforms:
    android:
      enable: true
      image_path: "assets/icons/web/icon-512.png"
      adaptive_background_color: '#000000'
      adaptive_foreground_image: "assets/icons/android/ic_launcher_foreground.png"
      adaptive_monochrome_image: "assets/icons/android/ic_launcher_monochrome.png"
    ios:
      enable: true
      image_path: "assets/icons/web/icon-512-maskable.png"
    web:
      enable: true
      image_path: "assets/icons/web/icon-512.png"
      favicon_path: "assets/icons/web/icon-512.png"
    macos:
      enable: true
      image_path: "assets/icons/web/icon-512-maskable.png"
    windows:
      enable: true
      image_path: "assets/icons/web/icon-512.png"
    linux:
      enable: true
      image_path: "assets/icons/web/icon-512.png"
flutter_intl:
  enabled: true
