name: Docker Build and Push

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Forgejo Container Registry
        uses: docker/login-action@v3
        with:
          registry: code.aes.schule
          username: ${{ secrets.FORGEJO_USERNAME }}
          password: ${{ secrets.FORGEJO_TOKEN }}


      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            code.aes.schule/aesmtk-app/aesapp:${{ github.sha }}
            code.aes.schule/aesmtk-app/aesapp:latest
          build-args: | # If you have build arguments
            BUILD_VERSION=${{ github.sha }}
        env:
          DOCKER_BUILDKIT: 1
