import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:sn_progress_dialog/progress_dialog.dart';

class Menu{
  Menu({required this.date, this.creationTime, this.umbestellbar, this.isAutoGenerated, this.hidden});
  DateTime date;
  DateTime? creationTime;
  List<MenuOption> selectableMenus = [];
  List<MenuOption> otherMenus = [];
  bool? umbestellbar;
  bool? isAutoGenerated;
  bool? hidden;
  
  Menu.fromJSON(Map menu)
      : date = DateTime.parse(menu["date"]),
        creationTime = DateTime.parse(menu["creation_time"]),
        umbestellbar = menu["umbestellbar"],
        isAutoGenerated = menu["is_auto_generated"],
        hidden = menu["hidden"]{
        if(menu["normal"]!=null)selectableMenus.add(MenuOption("Normal", menu["normal"]));
        if(menu["veggie"]!=null)selectableMenus.add(MenuOption("Vegetarisch", menu["veggie"]));
        if(menu["pasta"]!=null)selectableMenus.add(MenuOption("Pasta", menu["pasta"]));
        if(menu["dessert"]!=null)otherMenus.add(MenuOption("Nachtisch", menu["dessert"]));
        //selectableMenus.add(MenuOption("Großer Salatteller", "Salatbar"));
  }

  Future<bool> orderMeal(BuildContext context, String? mealCategory)async{
    bool success = false;
    ProgressDialog pd = ProgressDialog(context: context);
    ColorScheme scheme = Theme.of(context).colorScheme;
    String m = (mealCategory!=null)?'Bestelle "$mealCategory"...':"Abbestellen...";
    pd.show(msg: m, backgroundColor: scheme.surface, msgColor: scheme.onBackground, progressValueColor: scheme.primary,elevation: 0.0, msgMaxLines: 2,hideValue: true);
    await Future.delayed(Durations.extralong4);
    pd.update(msg: "Erfolgreich!",);
    pd.close(delay: 1000);
    return success;
  }

}

class MenuOption{
  MenuOption(this.category, this.menu);
  String category;
  String menu;
}