class Menu{
  Menu({required this.date, this.creationTime, this.normal, this.pasta, this.veggie, this.dessert, this.umbestellbar, this.isAutoGenerated, this.hidden});
  DateTime date;
  DateTime? creationTime;
  String? normal;
  String? pasta;
  String? veggie;
  String? dessert;
  bool? umbestellbar;
  bool? isAutoGenerated;
  bool? hidden;
  
  Menu.fromJSON(Map menu)
      : date = DateTime.parse(menu["date"]),
        creationTime = DateTime.parse(menu["creation_time"]),
        normal = menu["normal"],
        pasta = menu["pasta"],
        veggie = menu["veggie"],
        dessert = menu["dessert"],
        umbestellbar = menu["umbestellbar"],
        isAutoGenerated = menu["is_auto_generated"],
        hidden = menu["hidden"];
  
}