// coverage:ignore-file
// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: type=lint
// ignore_for_file: unused_element, deprecated_member_use, deprecated_member_use_from_same_package, use_function_type_syntax_for_parameters, unnecessary_const, avoid_init_to_null, invalid_override_different_default_values_named, prefer_expression_function_bodies, annotate_overrides, invalid_annotation_target, unnecessary_question_mark

part of 'mensa.dart';

// **************************************************************************
// FreezedGenerator
// **************************************************************************

T _$identity<T>(T value) => value;

final _privateConstructorUsedError = UnsupportedError(
    'It seems like you constructed your class using `MyClass._()`. This constructor is only meant to be used by freezed and you are not supposed to need it nor use it.\nPlease check the documentation here for more information: https://github.com/rrousselGit/freezed#custom-getters-and-methods');

Menu _$MenuFromJson(Map<String, dynamic> json) {
  return _Menu.fromJson(json);
}

/// @nodoc
mixin _$Menu {
  DateTime get date => throw _privateConstructorUsedError;
  set date(DateTime value) => throw _privateConstructorUsedError;
  @JsonKey(name: "creation_time")
  DateTime? get creationTime => throw _privateConstructorUsedError;
  @JsonKey(name: "creation_time")
  set creationTime(DateTime? value) => throw _privateConstructorUsedError;
  String? get normal => throw _privateConstructorUsedError;
  set normal(String? value) => throw _privateConstructorUsedError;
  String? get veggie => throw _privateConstructorUsedError;
  set veggie(String? value) => throw _privateConstructorUsedError;
  String? get pasta => throw _privateConstructorUsedError;
  set pasta(String? value) => throw _privateConstructorUsedError;
  String? get dessert => throw _privateConstructorUsedError;
  set dessert(String? value) => throw _privateConstructorUsedError;
  bool? get umbestellbar => throw _privateConstructorUsedError;
  set umbestellbar(bool? value) => throw _privateConstructorUsedError;
  @JsonKey(name: "is_auto_generated")
  bool? get isAutoGenerated => throw _privateConstructorUsedError;
  @JsonKey(name: "is_auto_generated")
  set isAutoGenerated(bool? value) => throw _privateConstructorUsedError;
  bool? get hidden => throw _privateConstructorUsedError;
  set hidden(bool? value) => throw _privateConstructorUsedError;
  @JsonKey(includeIfNull: false, includeFromJson: false)
  List<MenuOption>? get equalSelectableMenus =>
      throw _privateConstructorUsedError;
  @JsonKey(includeIfNull: false, includeFromJson: false)
  set equalSelectableMenus(List<MenuOption>? value) =>
      throw _privateConstructorUsedError;
  @JsonKey(includeIfNull: false, includeFromJson: false)
  List<MenuOption>? get otherSelectableMenus =>
      throw _privateConstructorUsedError;
  @JsonKey(includeIfNull: false, includeFromJson: false)
  set otherSelectableMenus(List<MenuOption>? value) =>
      throw _privateConstructorUsedError;
  @JsonKey(includeIfNull: false, includeFromJson: false)
  List<MenuOption>? get otherMenus => throw _privateConstructorUsedError;
  @JsonKey(includeIfNull: false, includeFromJson: false)
  set otherMenus(List<MenuOption>? value) => throw _privateConstructorUsedError;

  Map<String, dynamic> toJson() => throw _privateConstructorUsedError;
  @JsonKey(ignore: true)
  $MenuCopyWith<Menu> get copyWith => throw _privateConstructorUsedError;
}

/// @nodoc
abstract class $MenuCopyWith<$Res> {
  factory $MenuCopyWith(Menu value, $Res Function(Menu) then) =
      _$MenuCopyWithImpl<$Res, Menu>;
  @useResult
  $Res call(
      {DateTime date,
      @JsonKey(name: "creation_time") DateTime? creationTime,
      String? normal,
      String? veggie,
      String? pasta,
      String? dessert,
      bool? umbestellbar,
      @JsonKey(name: "is_auto_generated") bool? isAutoGenerated,
      bool? hidden,
      @JsonKey(includeIfNull: false, includeFromJson: false)
      List<MenuOption>? equalSelectableMenus,
      @JsonKey(includeIfNull: false, includeFromJson: false)
      List<MenuOption>? otherSelectableMenus,
      @JsonKey(includeIfNull: false, includeFromJson: false)
      List<MenuOption>? otherMenus});
}

/// @nodoc
class _$MenuCopyWithImpl<$Res, $Val extends Menu>
    implements $MenuCopyWith<$Res> {
  _$MenuCopyWithImpl(this._value, this._then);

  // ignore: unused_field
  final $Val _value;
  // ignore: unused_field
  final $Res Function($Val) _then;

  @pragma('vm:prefer-inline')
  @override
  $Res call({
    Object? date = null,
    Object? creationTime = freezed,
    Object? normal = freezed,
    Object? veggie = freezed,
    Object? pasta = freezed,
    Object? dessert = freezed,
    Object? umbestellbar = freezed,
    Object? isAutoGenerated = freezed,
    Object? hidden = freezed,
    Object? equalSelectableMenus = freezed,
    Object? otherSelectableMenus = freezed,
    Object? otherMenus = freezed,
  }) {
    return _then(_value.copyWith(
      date: null == date
          ? _value.date
          : date // ignore: cast_nullable_to_non_nullable
              as DateTime,
      creationTime: freezed == creationTime
          ? _value.creationTime
          : creationTime // ignore: cast_nullable_to_non_nullable
              as DateTime?,
      normal: freezed == normal
          ? _value.normal
          : normal // ignore: cast_nullable_to_non_nullable
              as String?,
      veggie: freezed == veggie
          ? _value.veggie
          : veggie // ignore: cast_nullable_to_non_nullable
              as String?,
      pasta: freezed == pasta
          ? _value.pasta
          : pasta // ignore: cast_nullable_to_non_nullable
              as String?,
      dessert: freezed == dessert
          ? _value.dessert
          : dessert // ignore: cast_nullable_to_non_nullable
              as String?,
      umbestellbar: freezed == umbestellbar
          ? _value.umbestellbar
          : umbestellbar // ignore: cast_nullable_to_non_nullable
              as bool?,
      isAutoGenerated: freezed == isAutoGenerated
          ? _value.isAutoGenerated
          : isAutoGenerated // ignore: cast_nullable_to_non_nullable
              as bool?,
      hidden: freezed == hidden
          ? _value.hidden
          : hidden // ignore: cast_nullable_to_non_nullable
              as bool?,
      equalSelectableMenus: freezed == equalSelectableMenus
          ? _value.equalSelectableMenus
          : equalSelectableMenus // ignore: cast_nullable_to_non_nullable
              as List<MenuOption>?,
      otherSelectableMenus: freezed == otherSelectableMenus
          ? _value.otherSelectableMenus
          : otherSelectableMenus // ignore: cast_nullable_to_non_nullable
              as List<MenuOption>?,
      otherMenus: freezed == otherMenus
          ? _value.otherMenus
          : otherMenus // ignore: cast_nullable_to_non_nullable
              as List<MenuOption>?,
    ) as $Val);
  }
}

/// @nodoc
abstract class _$$MenuImplCopyWith<$Res> implements $MenuCopyWith<$Res> {
  factory _$$MenuImplCopyWith(
          _$MenuImpl value, $Res Function(_$MenuImpl) then) =
      __$$MenuImplCopyWithImpl<$Res>;
  @override
  @useResult
  $Res call(
      {DateTime date,
      @JsonKey(name: "creation_time") DateTime? creationTime,
      String? normal,
      String? veggie,
      String? pasta,
      String? dessert,
      bool? umbestellbar,
      @JsonKey(name: "is_auto_generated") bool? isAutoGenerated,
      bool? hidden,
      @JsonKey(includeIfNull: false, includeFromJson: false)
      List<MenuOption>? equalSelectableMenus,
      @JsonKey(includeIfNull: false, includeFromJson: false)
      List<MenuOption>? otherSelectableMenus,
      @JsonKey(includeIfNull: false, includeFromJson: false)
      List<MenuOption>? otherMenus});
}

/// @nodoc
class __$$MenuImplCopyWithImpl<$Res>
    extends _$MenuCopyWithImpl<$Res, _$MenuImpl>
    implements _$$MenuImplCopyWith<$Res> {
  __$$MenuImplCopyWithImpl(_$MenuImpl _value, $Res Function(_$MenuImpl) _then)
      : super(_value, _then);

  @pragma('vm:prefer-inline')
  @override
  $Res call({
    Object? date = null,
    Object? creationTime = freezed,
    Object? normal = freezed,
    Object? veggie = freezed,
    Object? pasta = freezed,
    Object? dessert = freezed,
    Object? umbestellbar = freezed,
    Object? isAutoGenerated = freezed,
    Object? hidden = freezed,
    Object? equalSelectableMenus = freezed,
    Object? otherSelectableMenus = freezed,
    Object? otherMenus = freezed,
  }) {
    return _then(_$MenuImpl(
      date: null == date
          ? _value.date
          : date // ignore: cast_nullable_to_non_nullable
              as DateTime,
      creationTime: freezed == creationTime
          ? _value.creationTime
          : creationTime // ignore: cast_nullable_to_non_nullable
              as DateTime?,
      normal: freezed == normal
          ? _value.normal
          : normal // ignore: cast_nullable_to_non_nullable
              as String?,
      veggie: freezed == veggie
          ? _value.veggie
          : veggie // ignore: cast_nullable_to_non_nullable
              as String?,
      pasta: freezed == pasta
          ? _value.pasta
          : pasta // ignore: cast_nullable_to_non_nullable
              as String?,
      dessert: freezed == dessert
          ? _value.dessert
          : dessert // ignore: cast_nullable_to_non_nullable
              as String?,
      umbestellbar: freezed == umbestellbar
          ? _value.umbestellbar
          : umbestellbar // ignore: cast_nullable_to_non_nullable
              as bool?,
      isAutoGenerated: freezed == isAutoGenerated
          ? _value.isAutoGenerated
          : isAutoGenerated // ignore: cast_nullable_to_non_nullable
              as bool?,
      hidden: freezed == hidden
          ? _value.hidden
          : hidden // ignore: cast_nullable_to_non_nullable
              as bool?,
      equalSelectableMenus: freezed == equalSelectableMenus
          ? _value.equalSelectableMenus
          : equalSelectableMenus // ignore: cast_nullable_to_non_nullable
              as List<MenuOption>?,
      otherSelectableMenus: freezed == otherSelectableMenus
          ? _value.otherSelectableMenus
          : otherSelectableMenus // ignore: cast_nullable_to_non_nullable
              as List<MenuOption>?,
      otherMenus: freezed == otherMenus
          ? _value.otherMenus
          : otherMenus // ignore: cast_nullable_to_non_nullable
              as List<MenuOption>?,
    ));
  }
}

/// @nodoc
@JsonSerializable()
class _$MenuImpl extends _Menu {
  _$MenuImpl(
      {required this.date,
      @JsonKey(name: "creation_time") this.creationTime,
      this.normal,
      this.veggie,
      this.pasta,
      this.dessert,
      this.umbestellbar,
      @JsonKey(name: "is_auto_generated") this.isAutoGenerated,
      this.hidden,
      @JsonKey(includeIfNull: false, includeFromJson: false)
      this.equalSelectableMenus,
      @JsonKey(includeIfNull: false, includeFromJson: false)
      this.otherSelectableMenus,
      @JsonKey(includeIfNull: false, includeFromJson: false) this.otherMenus})
      : super._();

  factory _$MenuImpl.fromJson(Map<String, dynamic> json) =>
      _$$MenuImplFromJson(json);

  @override
  DateTime date;
  @override
  @JsonKey(name: "creation_time")
  DateTime? creationTime;
  @override
  String? normal;
  @override
  String? veggie;
  @override
  String? pasta;
  @override
  String? dessert;
  @override
  bool? umbestellbar;
  @override
  @JsonKey(name: "is_auto_generated")
  bool? isAutoGenerated;
  @override
  bool? hidden;
  @override
  @JsonKey(includeIfNull: false, includeFromJson: false)
  List<MenuOption>? equalSelectableMenus;
  @override
  @JsonKey(includeIfNull: false, includeFromJson: false)
  List<MenuOption>? otherSelectableMenus;
  @override
  @JsonKey(includeIfNull: false, includeFromJson: false)
  List<MenuOption>? otherMenus;

  @override
  String toString() {
    return 'Menu(date: $date, creationTime: $creationTime, normal: $normal, veggie: $veggie, pasta: $pasta, dessert: $dessert, umbestellbar: $umbestellbar, isAutoGenerated: $isAutoGenerated, hidden: $hidden, equalSelectableMenus: $equalSelectableMenus, otherSelectableMenus: $otherSelectableMenus, otherMenus: $otherMenus)';
  }

  @JsonKey(ignore: true)
  @override
  @pragma('vm:prefer-inline')
  _$$MenuImplCopyWith<_$MenuImpl> get copyWith =>
      __$$MenuImplCopyWithImpl<_$MenuImpl>(this, _$identity);

  @override
  Map<String, dynamic> toJson() {
    return _$$MenuImplToJson(
      this,
    );
  }
}

abstract class _Menu extends Menu {
  factory _Menu(
      {required DateTime date,
      @JsonKey(name: "creation_time") DateTime? creationTime,
      String? normal,
      String? veggie,
      String? pasta,
      String? dessert,
      bool? umbestellbar,
      @JsonKey(name: "is_auto_generated") bool? isAutoGenerated,
      bool? hidden,
      @JsonKey(includeIfNull: false, includeFromJson: false)
      List<MenuOption>? equalSelectableMenus,
      @JsonKey(includeIfNull: false, includeFromJson: false)
      List<MenuOption>? otherSelectableMenus,
      @JsonKey(includeIfNull: false, includeFromJson: false)
      List<MenuOption>? otherMenus}) = _$MenuImpl;
  _Menu._() : super._();

  factory _Menu.fromJson(Map<String, dynamic> json) = _$MenuImpl.fromJson;

  @override
  DateTime get date;
  set date(DateTime value);
  @override
  @JsonKey(name: "creation_time")
  DateTime? get creationTime;
  @JsonKey(name: "creation_time")
  set creationTime(DateTime? value);
  @override
  String? get normal;
  set normal(String? value);
  @override
  String? get veggie;
  set veggie(String? value);
  @override
  String? get pasta;
  set pasta(String? value);
  @override
  String? get dessert;
  set dessert(String? value);
  @override
  bool? get umbestellbar;
  set umbestellbar(bool? value);
  @override
  @JsonKey(name: "is_auto_generated")
  bool? get isAutoGenerated;
  @JsonKey(name: "is_auto_generated")
  set isAutoGenerated(bool? value);
  @override
  bool? get hidden;
  set hidden(bool? value);
  @override
  @JsonKey(includeIfNull: false, includeFromJson: false)
  List<MenuOption>? get equalSelectableMenus;
  @JsonKey(includeIfNull: false, includeFromJson: false)
  set equalSelectableMenus(List<MenuOption>? value);
  @override
  @JsonKey(includeIfNull: false, includeFromJson: false)
  List<MenuOption>? get otherSelectableMenus;
  @JsonKey(includeIfNull: false, includeFromJson: false)
  set otherSelectableMenus(List<MenuOption>? value);
  @override
  @JsonKey(includeIfNull: false, includeFromJson: false)
  List<MenuOption>? get otherMenus;
  @JsonKey(includeIfNull: false, includeFromJson: false)
  set otherMenus(List<MenuOption>? value);
  @override
  @JsonKey(ignore: true)
  _$$MenuImplCopyWith<_$MenuImpl> get copyWith =>
      throw _privateConstructorUsedError;
}

MenuOption _$MenuOptionFromJson(Map<String, dynamic> json) {
  return _MenuOption.fromJson(json);
}

/// @nodoc
mixin _$MenuOption {
  String get category => throw _privateConstructorUsedError;
  set category(String value) => throw _privateConstructorUsedError;
  String get menu => throw _privateConstructorUsedError;
  set menu(String value) => throw _privateConstructorUsedError;

  Map<String, dynamic> toJson() => throw _privateConstructorUsedError;
  @JsonKey(ignore: true)
  $MenuOptionCopyWith<MenuOption> get copyWith =>
      throw _privateConstructorUsedError;
}

/// @nodoc
abstract class $MenuOptionCopyWith<$Res> {
  factory $MenuOptionCopyWith(
          MenuOption value, $Res Function(MenuOption) then) =
      _$MenuOptionCopyWithImpl<$Res, MenuOption>;
  @useResult
  $Res call({String category, String menu});
}

/// @nodoc
class _$MenuOptionCopyWithImpl<$Res, $Val extends MenuOption>
    implements $MenuOptionCopyWith<$Res> {
  _$MenuOptionCopyWithImpl(this._value, this._then);

  // ignore: unused_field
  final $Val _value;
  // ignore: unused_field
  final $Res Function($Val) _then;

  @pragma('vm:prefer-inline')
  @override
  $Res call({
    Object? category = null,
    Object? menu = null,
  }) {
    return _then(_value.copyWith(
      category: null == category
          ? _value.category
          : category // ignore: cast_nullable_to_non_nullable
              as String,
      menu: null == menu
          ? _value.menu
          : menu // ignore: cast_nullable_to_non_nullable
              as String,
    ) as $Val);
  }
}

/// @nodoc
abstract class _$$MenuOptionImplCopyWith<$Res>
    implements $MenuOptionCopyWith<$Res> {
  factory _$$MenuOptionImplCopyWith(
          _$MenuOptionImpl value, $Res Function(_$MenuOptionImpl) then) =
      __$$MenuOptionImplCopyWithImpl<$Res>;
  @override
  @useResult
  $Res call({String category, String menu});
}

/// @nodoc
class __$$MenuOptionImplCopyWithImpl<$Res>
    extends _$MenuOptionCopyWithImpl<$Res, _$MenuOptionImpl>
    implements _$$MenuOptionImplCopyWith<$Res> {
  __$$MenuOptionImplCopyWithImpl(
      _$MenuOptionImpl _value, $Res Function(_$MenuOptionImpl) _then)
      : super(_value, _then);

  @pragma('vm:prefer-inline')
  @override
  $Res call({
    Object? category = null,
    Object? menu = null,
  }) {
    return _then(_$MenuOptionImpl(
      null == category
          ? _value.category
          : category // ignore: cast_nullable_to_non_nullable
              as String,
      null == menu
          ? _value.menu
          : menu // ignore: cast_nullable_to_non_nullable
              as String,
    ));
  }
}

/// @nodoc
@JsonSerializable()
class _$MenuOptionImpl implements _MenuOption {
  _$MenuOptionImpl(this.category, this.menu);

  factory _$MenuOptionImpl.fromJson(Map<String, dynamic> json) =>
      _$$MenuOptionImplFromJson(json);

  @override
  String category;
  @override
  String menu;

  @override
  String toString() {
    return 'MenuOption(category: $category, menu: $menu)';
  }

  @JsonKey(ignore: true)
  @override
  @pragma('vm:prefer-inline')
  _$$MenuOptionImplCopyWith<_$MenuOptionImpl> get copyWith =>
      __$$MenuOptionImplCopyWithImpl<_$MenuOptionImpl>(this, _$identity);

  @override
  Map<String, dynamic> toJson() {
    return _$$MenuOptionImplToJson(
      this,
    );
  }
}

abstract class _MenuOption implements MenuOption {
  factory _MenuOption(String category, String menu) = _$MenuOptionImpl;

  factory _MenuOption.fromJson(Map<String, dynamic> json) =
      _$MenuOptionImpl.fromJson;

  @override
  String get category;
  set category(String value);
  @override
  String get menu;
  set menu(String value);
  @override
  @JsonKey(ignore: true)
  _$$MenuOptionImplCopyWith<_$MenuOptionImpl> get copyWith =>
      throw _privateConstructorUsedError;
}
