// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA62woIwGhUHn282wIi2B1-yclGLY_LzeU',
    appId: '1:590479197727:web:8395586d20b6bc9372b72a',
    messagingSenderId: '590479197727',
    projectId: 'aesmtk-app-test',
    authDomain: 'aesmtk-app-test.firebaseapp.com',
    storageBucket: 'aesmtk-app-test.appspot.com',
    measurementId: 'G-EC0P7MV3NJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYbI3EdkpcK20AbiBZ8s5_Pw397sI9qOQ',
    appId: '1:590479197727:android:15ec15700a46a66572b72a',
    messagingSenderId: '590479197727',
    projectId: 'aesmtk-app-test',
    storageBucket: 'aesmtk-app-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpma7LORB0UNKchVjiFTdqeQMvY1Z3yS0',
    appId: '1:590479197727:ios:7f4c93e3eea0ec7072b72a',
    messagingSenderId: '590479197727',
    projectId: 'aesmtk-app-test',
    storageBucket: 'aesmtk-app-test.appspot.com',
    iosClientId: '590479197727-v0thg6q02d1v81qlpa2sbnitbhnh8fq6.apps.googleusercontent.com',
    iosBundleId: 'net.redsolver.aesapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpma7LORB0UNKchVjiFTdqeQMvY1Z3yS0',
    appId: '1:590479197727:ios:bbbe9bec967e96e372b72a',
    messagingSenderId: '590479197727',
    projectId: 'aesmtk-app-test',
    storageBucket: 'aesmtk-app-test.appspot.com',
    iosClientId: '590479197727-nvm07tdmbu5flbal4kl8v8l3kuoq0kfd.apps.googleusercontent.com',
    iosBundleId: 'net.redsolver.aesapp.RunnerTests',
  );
}
