name: Build binaries
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - run: flutter --version
    - run: flutter pub get
    - run: flutter build apk
    - uses: actions/upload-artifact@v1
      with:
        name: release-apk
        path: build/app/outputs/apk/release/app-release.apk
