name: Build binaries
on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Prepare Flutter-Env
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Prepare Android
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Get dependencies
        run: | 
          flutter --version
          flutter pub get
      - name: Enable Linux-Desktop
        run: flutter config --enable-linux-desktop
      - name: Build Android all Arch
        run: flutter build apk --release
      - name: Build Android split-per-abi
        run: flutter build apk --split-per-abi --release
      - name: Build Android appbundle
        run: flutter build appbundle --release
      - name: Prepare Linux-Desktop
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
          sudo apt-get update -y
          sudo apt-get install -y tar clang cmake ninja-build pkg-config libgtk-3-dev make python3-pip python3-setuptools desktop-file-utils libgdk-pixbuf2.0-dev fakeroot strace fuse libunwind-dev locate patchelf gir1.2-appindicator3-0.1 libappindicator3-1 libappindicator3-dev libsecret-1-0 libjsoncpp25 libsecret-1-dev libjsoncpp-dev libnotify-bin libnotify-dev mpv libmpv-dev

      - name: Install AppImage Tool
        run: |
          wget -O appimagetool "https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage"
          chmod +x appimagetool
          mv appimagetool /usr/local/bin/
      - name: Build Linux-Desktop
        run: | 
          dart pub global activate flutter_distributor
          alias dpkg-deb="dpkg-deb --Zxz"
          flutter_distributor package --platform=linux --targets=deb
          flutter_distributor package --platform=linux --targets=appimage
          flutter_distributor package --platform=linux --targets=rpm
      - name: Move and rename builds
        run: |
          ls
          mv build/app/outputs/flutter-apk/app-release.apk aesapp-android-all-arch-$GITHUB_REF_NAME.apk
          mv build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk aesapp-android-armeabi-v7a-$GITHUB_REF_NAME.apk
          mv build/app/outputs/flutter-apk/app-arm64-v8a-release.apk aesapp-android-arm64-v8a-$GITHUB_REF_NAME.apk
          mv build/app/outputs/flutter-apk/app-x86_64-release.apk aesapp-android-x86_64-$GITHUB_REF_NAME.apk
          mv build/app/outputs/bundle/release/app-release.aab aesapp-android-all-arch-bundle-$GITHUB_REF_NAME.aab
          mv dist/**/aesapp-*-linux.deb aesapp-linux-x86_64-$GITHUB_REF_NAME.deb
          mv dist/**/aesapp-*-linux.rpm aesapp-linux-x86_64-$GITHUB_REF_NAME.rpm
          mv dist/**/aesapp-*-linux.AppImage aesapp-linux-x86_64-$GITHUB_REF_NAME.AppImage
          ls
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./aesapp-android-all-arch-$GITHUB_REF_NAME.apk
            ./aesapp-android-armeabi-v7a-$GITHUB_REF_NAME.apk
            ./aesapp-android-arm64-v8a-$GITHUB_REF_NAME.apk
            ./aesapp-android-x86_64-$GITHUB_REF_NAME.apk
            ./aesapp-android-all-arch-bundle-$GITHUB_REF_NAME.aab
            ./aesapp-linux-x86_64-$GITHUB_REF_NAME.deb
            ./aesapp-linux-x86_64-$GITHUB_REF_NAME.rpm
            ./aesapp-linux-x86_64-$GITHUB_REF_NAME.AppImage
            
