name: Build binaries
on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - run: |
          uname -a
          pwd
          sudo apt-get update -y
          sudo apt install tree -y
      - name: Checkout
        uses: actions/checkout@v3
      - name: Prepare Flutter-Env
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Prepare Android
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Get dependencies
        run: | 
          flutter --version
          flutter pub get
      - name: Build Android all Arch
        run: flutter build apk --release
      - name: Build Android split-per-abi
        run: flutter build apk --split-per-abi --release
      - name: Build Android appbundle
        run: flutter build appbundle --release
      - name: Move and rename builds
        run: |
          ls
          tree
          mv build/app/outputs/flutter-apk/app-release.apk aesapp-android-all-arch-$GITHUB_REF_NAME.apk
          mv build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk aesapp-android-armeabi-v7a-$GITHUB_REF_NAME.apk
          mv build/app/outputs/flutter-apk/app-arm64-v8a-release.apk aesapp-android-arm64-v8a-$GITHUB_REF_NAME.apk
          mv build/app/outputs/flutter-apk/app-x86_64-release.apk aesapp-android-x86_64-$GITHUB_REF_NAME.apk
          mv build/app/outputs/bundle/release/app-release.aab aesapp-android-all-arch-bundle-$GITHUB_REF_NAME.aab
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            aesapp-android-all-arch-$GITHUB_REF_NAME.apk
            aesapp-android-armeabi-v7a-$GITHUB_REF_NAME.apk
            aesapp-android-arm64-v8a-$GITHUB_REF_NAME.apk
            aesapp-android-x86_64-$GITHUB_REF_NAME.apk
            aesapp-android-all-arch-bundle-$GITHUB_REF_NAME.aab
            aesapp-linux-x86_64-$GITHUB_REF_NAME.deb
            aesapp-linux-x86_64-$GITHUB_REF_NAME.rpm
            aesapp-linux-x86_64-$GITHUB_REF_NAME.AppImage
            
